### ISSUE TITLE
list of videos not shown at first for some users

### ISSUE THREAD

**Issue by bbbo** [flowplayer/flowplayer-ovp-for-wordpress#2]
see https://flowplayer.slack.com/archives/C0EB1GRT2/p1552936290003200 :

"the platform embed plugin doesn't seem to connect to my OVP library at first attempt, it just offers to upload clips? Once I select a clip from my desktop (which apparently never makes it to OVP), I get a list of existing videos though, and can embed them."

![image](https://user-images.githubusercontent.com/1395672/54585048-5871c680-4a19-11e9-93e6-666390bac7d9.png)

![image](https://user-images.githubusercontent.com/1395672/54585069-61fb2e80-4a19-11e9-9a56-30230cfde9d6.png)

**Comment by underdude** [comment]
Quick update. This seems to be the result if:

1. Api keys are not set
2. Connection to api fails
3. There's no videos uploaded in OVP

Fixed the first one already, the others need some work still.

**Comment by bbbo** [comment]
hm, I did set the API keys and have videos, stillt he effect showed. I'll try with a different WP install over the weekend.
